version: '2'

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  website:
    build: .
    command: puma -C config/puma.rb
    ports:
      - '3000:3000'
    volumes:
      - '.:/my_dockerized_app'
    links:
      - rabbitmq
      - redis
      - db
    depends_on:
      - rabbitmq
      - redis
      - db
