# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae2ab06559001eb71ab5a3c6fe5d57fea87d756461451478912a984d8ac55932fea78a475e4c809735391a51cdd9ed62a7f1576ca8133e4cea1ae1fa34560727

test:
  secret_key_base: f58738fa6a65654afe61421c8369fcaa879965f5bf50937229c7bf0fbb21d84626ef5b767c29145e26ad0f1cd6e1e9cabfc0ac0e3cc3efe2622c85a627245060

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
